import { describe, expect, it } from "vitest";
import { buildHandoverDocumentHistory, collapseHandoverDuplicateMatches, findExistingMatchForHandover } from "@/lib/handoverHistory";
import type { MatchingHistoryRecord } from "@/types";

const worker = { id: "worker-1", name: "조윤옥", phone: "010-1111-2222" };

describe("handover history", () => {
  it("keeps the original service start when the handover document names the already active worker", () => {
    const result = buildHandoverDocumentHistory({
      entries: [{ id: "existing", workerId: worker.id, workerName: worker.name, workerPhone: worker.phone, serviceStartDate: "2026-09-08", serviceEndDate: null, reason: "추가" }],
      previousWorkerId: worker.id,
      nextWorker: worker,
      handoverDate: "2026-09-11",
      takeoverDate: "2026-09-11",
      reasonDetail: "서류 작성",
    });

    expect(result).toHaveLength(1);
    expect(result[0].serviceStartDate).toBe("2026-09-08");
    expect(result[0].serviceEndDate).toBeNull();
  });

  it("reuses a normal active match instead of adding a handover-generated duplicate", () => {
    const records: Array<MatchingHistoryRecord & { id: string }> = [
      { id: "original", type: "매칭", userId: "user-1", userName: "이용자", userPhone: "", workerId: worker.id, workerName: worker.name, workerPhone: worker.phone, date: "2026-09-08" },
    ];
    expect(findExistingMatchForHandover(records, "user-1", worker.id)?.id).toBe("original");
  });

  it("hides only the duplicate matching row generated by a handover document", () => {
    const base: MatchingHistoryRecord = { type: "매칭", userId: "user-1", userName: "이용자", userPhone: "", workerId: worker.id, workerName: worker.name, workerPhone: worker.phone, date: "2026-09-08" };
    const result = collapseHandoverDuplicateMatches([
      { ...base, id: "original" },
      { ...base, id: "duplicate", date: "2026-09-11", notes: "인계·인수서 작성 (조윤옥 → 조윤옥) / 사유: 서류" },
    ]);
    expect(result.map((record) => record.id)).toEqual(["original"]);
  });

  it("keeps a later handover match when the earlier service was actually released", () => {
    const base: MatchingHistoryRecord = { type: "매칭", userId: "user-1", userName: "이용자", userPhone: "", workerId: worker.id, workerName: worker.name, workerPhone: worker.phone, date: "2026-01-01" };
    const result = collapseHandoverDuplicateMatches([
      { ...base, id: "original" },
      { ...base, id: "release", type: "해제", date: "2026-01-01", endDate: "2026-06-30" },
      { ...base, id: "restart", date: "2026-09-11", notes: "인계·인수서 작성 (이전지원 → 조윤옥) / 사유: 재매칭" },
    ]);
    expect(result.map((record) => record.id)).toContain("restart");
  });
});
