import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { DndContext, KeyboardSensor, PointerSensor, TouchSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { Copy, GripVertical, ImagePlus, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { EVENT_FORM_FIELD_LABELS, createEventFormId, getEventFormUsage, sortEventFormFields, validateEventFormForPublishing } from "@/lib/eventForms";
import { eventFormApi, loadEventForm, uploadEventFormImage } from "@/lib/eventFormSparkApi";
import type { EventFormField, EventFormFieldType, EventFormSlot } from "@/types/eventForms";
import { useToast } from "@/hooks/use-toast";
import { EventFormImage } from "@/components/EventFormImage";
import { createPublicEventFormUrl } from "@/lib/publicEventFormUrl";

const FIELD_TYPES = Object.keys(EVENT_FORM_FIELD_LABELS) as EventFormFieldType[];

function newField(type: EventFormFieldType, order: number): EventFormField {
  const choices = ["singleChoice", "multipleChoice", "dropdown"].includes(type) ? ["선택지 1", "선택지 2"] : type === "attendance" ? ["참석", "불참", "미정"] : [];
  return { id: createEventFormId("field"), type, title: EVENT_FORM_FIELD_LABELS[type], required: false, visible: true, order, options: choices.map((label, index) => ({ id: createEventFormId("option"), label, order: index, enabled: true })), ...(type === "consent" ? { consentText: "개인정보 수집·이용 안내문을 입력하세요.", consentVersion: "1", consentRequired: true } : {}) };
}

function SortableField({ field, onChange, onDelete, onCopy, formId }: { field: EventFormField; onChange: (value: EventFormField) => void; onDelete: () => void; onCopy: () => void; formId: string }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: field.id });
  const style = { transform: CSS.Transform.toString(transform), transition };
  const update = (patch: Partial<EventFormField>) => onChange({ ...field, ...patch });
  const choice = ["singleChoice", "multipleChoice", "dropdown", "attendance"].includes(field.type);
  const upload = async (file?: File, optionId?: string) => {
    if (!file) return;
    const alt = window.prompt("이미지 대체 설명을 입력하세요. 사진만 있는 선택지는 필수입니다.", field.title) || "";
    if (!alt.trim()) return;
    try {
      const image = await uploadEventFormImage(formId, file, alt);
      if (optionId) update({ options: field.options?.map((option) => option.id === optionId ? { ...option, image } : option) });
      else update({ image });
    } catch (error) { window.alert(error instanceof Error ? error.message : "이미지 업로드에 실패했습니다."); }
  };
  return <Card ref={setNodeRef} style={style} className={isDragging ? "opacity-60 shadow-xl" : ""}>
    <CardHeader className="space-y-3 pb-3"><div className="flex items-center gap-2"><button type="button" className="touch-none cursor-grab p-2 text-muted-foreground" aria-label="문항 순서 이동" {...attributes} {...listeners}><GripVertical className="h-5 w-5" /></button><span className="rounded bg-muted px-2 py-1 text-xs">{EVENT_FORM_FIELD_LABELS[field.type]}</span><div className="ml-auto flex gap-1"><Button type="button" size="icon" variant="ghost" onClick={onCopy} aria-label="복제"><Copy className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" onClick={onDelete} aria-label="삭제"><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div><Input value={field.title} onChange={(event) => update({ title: event.target.value })} placeholder="문항 제목" disabled={field.type === "divider"} /><Textarea value={field.description || ""} onChange={(event) => update({ description: event.target.value })} placeholder="문항 상세설명 (선택, 여러 줄 입력 가능)" /></CardHeader>
    <CardContent className="space-y-4">
      <div className="flex flex-wrap gap-5 text-sm"><label className="flex items-center gap-2"><Checkbox checked={field.visible} onCheckedChange={(checked) => update({ visible: checked === true })} />표시</label>{!["notice", "divider"].includes(field.type) && <label className="flex items-center gap-2"><Switch aria-label={`${field.title} 필수 입력`} checked={field.required} onCheckedChange={(checked) => update({ required: checked === true, ...(field.type === "consent" ? { consentRequired: checked === true } : {}) })} />필수 입력</label>}<label className="cursor-pointer rounded border px-3 py-1.5"><ImagePlus className="mr-1 inline h-4 w-4" />{field.image ? "이미지 교체" : "문항 이미지"}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(event.target.files?.[0])} /></label>{field.image && <Button type="button" size="sm" variant="ghost" onClick={() => update({ image: undefined })}>이미지 삭제</Button>}</div>
      {field.image && <div className="space-y-2"><EventFormImage image={field.image} className="max-h-48 rounded" /><label className="text-sm">이미지 대체 설명<Input value={field.image.alt} onChange={(e) => update({ image: field.image ? { ...field.image, alt: e.target.value } : undefined })} /></label></div>}
      {!["notice", "divider", "consent"].includes(field.type) && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">입력 예시<Input value={field.placeholder || ""} onChange={(e) => update({ placeholder: e.target.value })} /></label>{["shortText", "longText", "name", "phone", "email"].includes(field.type) && <label className="text-sm">최대 글자 수<Input type="number" min={1} max={field.type === "longText" ? 5000 : field.type === "email" ? 320 : field.type === "name" ? 100 : field.type === "phone" ? 30 : 500} value={field.maxLength || ""} onChange={(e) => update({ maxLength: e.target.valueAsNumber || undefined })} /></label>}</div>}
      {field.type === "date" && <div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">선택 시작일<Input type="date" value={field.dateMin || ""} onChange={(e) => update({ dateMin: e.target.value })} /></label><label className="text-sm">선택 종료일<Input type="date" value={field.dateMax || ""} onChange={(e) => update({ dateMax: e.target.value })} /></label></div><div className="flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><Checkbox checked={field.allowPast !== false} onCheckedChange={(checked) => update({ allowPast: checked === true })} />과거 날짜 허용</label><label className="flex items-center gap-2"><Checkbox checked={field.allowFuture !== false} onCheckedChange={(checked) => update({ allowFuture: checked === true })} />미래 날짜 허용</label></div></div>}
      {choice && field.allowOther && <div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm"><Checkbox checked disabled />기타 선택 시 내용 필수</label><label className="text-sm">기타 최대 글자 수<Input type="number" min={1} value={field.otherMaxLength || ""} onChange={(e) => update({ otherMaxLength: e.target.valueAsNumber || undefined })} /></label></div>}
      {field.type === "number" && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">최솟값<Input type="number" value={field.min ?? ""} onChange={(e) => update({ min: Number.isNaN(e.target.valueAsNumber) ? undefined : e.target.valueAsNumber })} /></label><label className="text-sm">최댓값<Input type="number" value={field.max ?? ""} onChange={(e) => update({ max: Number.isNaN(e.target.valueAsNumber) ? undefined : e.target.valueAsNumber })} /></label></div>}
      {field.type === "consent" && <div className="space-y-3"><Textarea value={field.consentText || ""} onChange={(e) => update({ consentText: e.target.value })} placeholder="동의 안내문" /><label className="flex items-center gap-2 text-sm"><Checkbox checked={field.consentRequired} onCheckedChange={(checked) => update({ consentRequired: checked === true, required: checked === true })} />필수 동의</label></div>}
      {choice && <div className="space-y-2">{(field.options || []).map((option, index) => <div key={option.id} className="flex flex-wrap items-center gap-2 rounded border p-2"><div className="flex gap-1"><Button type="button" size="icon" variant="ghost" disabled={index === 0} onClick={() => update({ options: arrayMove(field.options || [], index, index - 1).map((item, order) => ({ ...item, order })) })}>↑</Button><Button type="button" size="icon" variant="ghost" disabled={index === (field.options?.length || 0) - 1} onClick={() => update({ options: arrayMove(field.options || [], index, index + 1).map((item, order) => ({ ...item, order })) })}>↓</Button></div><Input className="min-w-40 flex-1" value={option.label} onChange={(e) => update({ options: field.options?.map((item) => item.id === option.id ? { ...item, label: e.target.value } : item) })} />{option.image && <EventFormImage image={option.image} className="h-14 w-20 rounded" />}<label className="cursor-pointer text-xs"><ImagePlus className="inline h-4 w-4" /><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(event.target.files?.[0], option.id)} /></label>{option.image && <Button type="button" size="sm" variant="ghost" onClick={() => update({ options: field.options?.map((item) => item.id === option.id ? { ...item, image: undefined } : item) })}>사진 삭제</Button>}<Button type="button" size="icon" variant="ghost" onClick={() => update({ options: field.options?.filter((item) => item.id !== option.id).map((item, order) => ({ ...item, order })) })}><Trash2 className="h-4 w-4" /></Button></div>)}<Button type="button" size="sm" variant="outline" onClick={() => update({ options: [...(field.options || []), { id: createEventFormId("option"), label: `선택지 ${(field.options?.length || 0) + 1}`, order: field.options?.length || 0, enabled: true }] })}><Plus className="mr-1 h-4 w-4" />선택지</Button><label className="ml-3 inline-flex items-center gap-2 text-sm"><Checkbox checked={field.allowOther} onCheckedChange={(checked) => update({ allowOther: checked === true })} />기타 의견</label>{field.type === "multipleChoice" && <div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">최소 선택 수<Input type="number" min={0} value={field.minSelections || ""} onChange={(e) => update({ minSelections: e.target.valueAsNumber || undefined })} /></label><label className="text-sm">최대 선택 수<Input type="number" min={1} value={field.maxSelections || ""} onChange={(e) => update({ maxSelections: e.target.valueAsNumber || undefined })} /></label></div>}</div>}
    </CardContent>
  </Card>;
}

export default function EventFormEditor() {
  const { formId = "" } = useParams();
  const [form, setForm] = useState<(EventFormSlot & { draftFields: EventFormField[] }) | null>(null);
  const [fields, setFields] = useState<EventFormField[]>([]);
  const [busy, setBusy] = useState(false);
  const [preview, setPreview] = useState(false);
  const { toast } = useToast();
  const navigate = useNavigate();
  const sensors = useSensors(useSensor(PointerSensor), useSensor(TouchSensor, { activationConstraint: { delay: 180, tolerance: 8 } }), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));

  useEffect(() => { void loadEventForm(formId).then((loaded) => { setForm(loaded); setFields(sortEventFormFields(loaded?.draftFields || [])); }); }, [formId]);
  const answerFields = useMemo(() => fields.filter((field) => field.visible && !["notice", "divider"].includes(field.type)), [fields]);
  if (!form) return <div className="py-16 text-center">폼을 불러오는 중...</div>;
  const updateForm = (patch: Partial<EventFormSlot>) => setForm({ ...form, ...patch });
  const uploadPoster = async (file?: File) => {
    if (!file) return;
    const alt = window.prompt("포스터 대체 설명", `${form.title} 포스터`) || "";
    if (!alt.trim()) return;
    try { updateForm({ poster: await uploadEventFormImage(formId, file, alt) }); }
    catch (error) { toast({ title: "포스터 업로드 실패", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); }
  };
  const normalize = (items: EventFormField[]) => items.map((item, order) => ({ ...item, order }));
  const addField = (type: EventFormFieldType) => {
    if (fields.length >= 100) { toast({ title: "문항 수 제한", description: "Spark 무료 운영 모드에서는 문항을 최대 100개까지 만들 수 있습니다.", variant: "destructive" }); return; }
    setFields([...fields, newField(type, fields.length)]);
  };
  const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const oldIndex = fields.findIndex((item) => item.id === active.id); const newIndex = fields.findIndex((item) => item.id === over.id); setFields(normalize(arrayMove(fields, oldIndex, newIndex))); };
  const save = async () => { setBusy(true); try { await eventFormApi.saveDraft({ ...form, formId, fields }); toast({ title: "임시 저장했습니다" }); } catch (error) { toast({ title: "저장 실패", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setBusy(false); } };
  const publish = async () => { const issues = validateEventFormForPublishing(fields); if (issues.length) return toast({ title: "공개 전 확인", description: issues.join("\n"), variant: "destructive" }); setBusy(true); try { await eventFormApi.saveDraft({ ...form, formId, fields }); await eventFormApi.publish(formId); updateForm({ status: "open" }); toast({ title: "접수를 시작했습니다" }); } catch (error) { toast({ title: "공개 실패", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setBusy(false); } };
  const shareUrl = createPublicEventFormUrl(form.publicToken);
  const usage = getEventFormUsage(fields, form.poster, form.expectedTargetCount || 0);
  const formatSize = (bytes: number) => bytes < 1024 ? `${bytes}B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)}KB` : `${(bytes / 1024 / 1024).toFixed(2)}MB`;
  return <section className="mx-auto max-w-5xl space-y-5">
    <div className="flex flex-wrap items-center gap-2"><Button variant="outline" onClick={() => navigate("/event-forms")}>목록</Button><div className="ml-auto flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPreview(!preview)}>{preview ? "미리보기 닫기" : "미리보기"}</Button><Button variant="outline" onClick={() => void save()} disabled={busy}>임시 저장</Button><Button onClick={() => void publish()} disabled={busy}>저장 후 접수 시작</Button><Button asChild variant="secondary"><Link to={`/event-forms/${formId}/results`}>결과 보기</Link></Button></div></div>
    <Card><CardHeader><CardTitle>대표 포스터</CardTitle></CardHeader><CardContent className="space-y-3"><label className="inline-flex cursor-pointer items-center rounded border px-3 py-2"><ImagePlus className="mr-2 h-4 w-4" />{form.poster ? "대표 포스터 교체" : "대표 포스터 추가"}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void uploadPoster(e.target.files?.[0])} /></label>{form.poster && <><EventFormImage image={form.poster} className="max-h-72 rounded" /><Button type="button" size="sm" variant="ghost" onClick={() => updateForm({ poster: null })}>포스터 삭제</Button></>}</CardContent></Card>
    <Card><CardHeader><CardTitle>폼 기본 정보</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">제목<Input value={form.title} onChange={(e) => updateForm({ title: e.target.value })} /></label><label className="sm:col-span-2">안내 설명<Textarea value={form.description} onChange={(e) => updateForm({ description: e.target.value })} /></label><label>행사·교육 일시<Input type="datetime-local" value={form.eventDateTime || ""} onChange={(e) => updateForm({ eventDateTime: e.target.value })} /></label><label>장소<Input value={form.location || ""} onChange={(e) => updateForm({ location: e.target.value })} /></label><label>신청 시작<Input type="datetime-local" value={form.applicationStartAt || ""} onChange={(e) => updateForm({ applicationStartAt: e.target.value })} /></label><label>신청 마감<Input type="datetime-local" value={form.applicationEndAt || ""} onChange={(e) => updateForm({ applicationEndAt: e.target.value })} /></label><label>예상 대상 인원 (선택)<Input type="number" min={1} max={100000} value={form.expectedTargetCount || ""} onChange={(e) => updateForm({ expectedTargetCount: e.target.value === "" ? 0 : e.target.valueAsNumber })} /></label><label className="sm:col-span-2">제출 완료 안내<Input value={form.completionMessage} onChange={(e) => updateForm({ completionMessage: e.target.value })} /></label><label>중복 처리<select className="mt-1 h-10 w-full rounded border bg-background px-3" value={form.duplicatePolicy} onChange={(e) => updateForm({ duplicatePolicy: e.target.value as EventFormSlot["duplicatePolicy"] })}><option value="none">확인 안 함</option><option value="warn">경고만 (권장)</option><option value="block">익명 계정 기준 차단</option></select></label><label>중복 확인 문항<select className="mt-1 h-10 w-full rounded border bg-background px-3" value={form.duplicateFieldId || ""} onChange={(e) => updateForm({ duplicateFieldId: e.target.value || undefined })}><option value="">브라우저 기록만</option>{answerFields.filter((field) => ["phone", "email", "shortText"].includes(field.type)).map((field) => <option key={field.id} value={field.id}>{field.title}</option>)}</select></label><p className="sm:col-span-2 rounded bg-amber-50 p-3 text-xs text-amber-900">무료 운영 모드에서는 브라우저·회차별 익명 계정 기준으로만 재제출을 제한합니다. 연락처 중복은 결과 화면에서 경고하며 서버 수준 연락처 강제 차단은 제공하지 않습니다.</p><div className="sm:col-span-2 rounded bg-muted p-3 text-sm"><strong>공유 주소</strong><div className="mt-1 break-all">{shareUrl || "저장 후 생성됩니다."}</div>{shareUrl && <Button className="mt-2" size="sm" variant="outline" onClick={() => void navigator.clipboard.writeText(shareUrl)}>주소 복사</Button>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>무료 한도 보호</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm sm:grid-cols-2"><p>문항: <strong>{usage.fieldCount}/100</strong></p><p>이미지: <strong>{usage.imageCount}/12</strong></p><p>현재 편집 이미지 합계(공개 시): <strong>{formatSize(usage.publicImageBytes)}/2MB</strong></p><p>예상 월 이미지 전송량: <strong>{formatSize(usage.estimatedMonthlyTransferBytes)}</strong></p><p>Firestore 저장량 상한 추정: <strong>{formatSize(usage.estimatedFirestoreStorageUpperBoundBytes)}</strong></p><p className="sm:col-span-2 text-xs text-muted-foreground">저장량은 현재 이미지와 예상 인원 모두가 응답 최대치 50KB를 사용한다고 가정한 보수적 상한입니다. Spark 무료 한도를 넘으면 과금되는 것이 아니라 Firebase 서비스가 제한될 수 있습니다.</p></CardContent></Card>
    <div className="flex flex-wrap gap-2">{FIELD_TYPES.map((type) => <Button key={type} type="button" size="sm" variant="outline" onClick={() => addField(type)}><Plus className="mr-1 h-3 w-3" />{EVENT_FORM_FIELD_LABELS[type]}</Button>)}</div>
    {preview && <Card className="border-primary/30 bg-muted/30"><CardHeader><CardTitle>{form.title || "제목 없음"}</CardTitle><p className="whitespace-pre-wrap text-sm text-muted-foreground">{form.description}</p></CardHeader><CardContent className="space-y-3">{sortEventFormFields(fields).filter((field) => field.visible).map((field) => field.type === "divider" ? <hr key={field.id} /> : <div key={field.id} className="rounded border bg-background p-3"><strong>{field.title || "제목 없음"}{(field.required || field.consentRequired) && <span className="text-destructive"> *</span>}</strong>{field.description && <p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{field.description}</p>}<EventFormImage image={field.image} className="mt-2 max-h-40 rounded" /><p className="mt-2 text-xs text-muted-foreground">{EVENT_FORM_FIELD_LABELS[field.type]} 미리보기</p></div>)}</CardContent></Card>}
    <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><SortableContext items={fields.map((field) => field.id)} strategy={verticalListSortingStrategy}><div className="space-y-4">{fields.map((field) => <SortableField key={field.id} field={field} formId={formId} onChange={(value) => setFields(fields.map((item) => item.id === field.id ? value : item))} onDelete={() => setFields(normalize(fields.filter((item) => item.id !== field.id)))} onCopy={() => setFields([...fields, { ...field, id: createEventFormId("field"), order: fields.length, options: field.options?.map((option) => ({ ...option, id: createEventFormId("option") })) }])} />)}</div></SortableContext></DndContext>
    {fields.length === 0 && <div className="rounded border border-dashed p-12 text-center text-muted-foreground">위 버튼에서 필요한 문항을 추가하세요. 이름·연락처·주소는 자동으로 강제되지 않습니다.</div>}
    <div className="flex flex-wrap gap-2 border-t pt-4"><Button onClick={() => void save()} disabled={busy}>임시 저장</Button><Button onClick={() => void publish()} disabled={busy}>접수 시작</Button><Button variant="outline" onClick={async () => { await eventFormApi.setStatus(formId, "closed"); updateForm({ status: "closed" }); }}>접수 마감</Button><Button variant="outline" onClick={async () => { if (!confirm("현재 회차와 응답을 보관하고 같은 링크로 새 회차를 시작할까요?")) return; const name = prompt("새 회차 이름", "새 회차") || "새 회차"; await eventFormApi.startRound(formId, name); toast({ title: "새 회차를 만들었습니다" }); window.location.reload(); }}>새 회차 시작</Button><Button variant="ghost" onClick={async () => { const count = await eventFormApi.cleanupUnusedImages(formId); toast({ title: "미사용 이미지 정리", description: `${count}개를 정리했습니다. 과거 회차에서 참조하는 이미지는 보존했습니다.` }); }}>미사용 이미지 수동 정리</Button></div>
  </section>;
}
